package main

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"net/http"
	"os"
	"os/exec"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/bootdotdev/learn-file-storage-s3-golang-starter/internal/auth"
	"github.com/google/uuid"
)

func (cfg *apiConfig) handlerUploadVideo(w http.ResponseWriter, r *http.Request) {
	// TODO: implement the upload here
	const maxMemory int64 = 1 << 30
	http.MaxBytesReader(w, r.Body, maxMemory)

	// Extract the videoID from the URL path parameters and parse it as a UUID
	videoIDString := r.PathValue("videoID")
	videoID, err := uuid.Parse(videoIDString)
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Invalid ID", err)
		return
	}

	// Authenticate the user to get a userID
	token, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Couldn't find JWT", err)
		return
	}

	userID, err := auth.ValidateJWT(token, cfg.jwtSecret)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Couldn't validate JWT", err)
		return
	}

	metadata, err := cfg.db.GetVideo(videoID)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Unable to read video meta data from db", err)
		return
	}

	// check video ownership
	if userID != metadata.UserID {
		respondWithError(w, http.StatusUnauthorized, "Authorization Error: User does not own this video", err)
		return
	}

	file, header, err := r.FormFile("video")
	if err != nil {
		respondWithError(w, http.StatusBadRequest, "Unable to parse thumbnail form file", err)
		return
	}
	defer file.Close()

	mediaType := header.Header.Get("Content-Type")
	mediaType, _, err = mime.ParseMediaType(mediaType)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Failed to parse content type", err)
		return
	}

	if mediaType != "video/mp4" {
		respondWithError(w, http.StatusBadRequest, "Invalid file media type", err)
		return
	}

	tempFile, err := os.CreateTemp("", "tubely-upload.mp4")
	defer os.Remove("tubely-upload.mp4")
	defer tempFile.Close()
	// copy uploaded file content into temp file
	io.Copy(tempFile, file)

	// Reset the tempFile's file pointer to the beginning - this will allow us to read the file again from the beginning
	tempFile.Seek(0, io.SeekStart)

	// 1. Define a 32-byte slice (256 bits)
	bytes := make([]byte, 32)
	// 2. Fill the slice with random data from crypto/rand
	if _, err = rand.Read(bytes); err != nil {
		respondWithError(w, http.StatusInternalServerError, "Error generating random bytes:", err)
		return
	}

	// 3. Convert bytes to a 64-char hexadecimal string
	hexString := hex.EncodeToString(bytes)
	fileKey := hexString + ".mp4"

	s3ObjectParams := s3.PutObjectInput{
		Bucket:      &(cfg.s3Bucket),
		Key:         &fileKey,
		Body:        tempFile,
		ContentType: &mediaType,
	}
	cfg.s3Client.PutObject(r.Context(), &s3ObjectParams)
	videoURL := fmt.Sprintf("https://%s.s3.%s.amazonaws.com/%s", cfg.s3Bucket, cfg.s3Region, fileKey)
	metadata.VideoURL = &videoURL
	if err := cfg.db.UpdateVideo(metadata); err != nil {
		respondWithError(w, http.StatusBadRequest, "Video not exist in db", err)
		return
	}
}

func getVideoAspectRatio(filePath string) (string, error) {
	// ffprobe -v error -print_format json -show_streams PATH_TO_VIDEO
	// command name: ffprobe, arguments: -v error -print_format json -show_streams PATH_TO_VIDEO
	args := []string{"-v", "error", "-print_format", "json", "-show_streams", filePath}
	cmd := exec.Command("ffprobe", args...)
	var b bytes.Buffer // A Buffer needs no initialization.
	cmd.Stdout = &b    // Set the resulting exec.Cmd's Stdout field to a pointer to a new bytes.Buffer
	cmd.Run()

	type AutoGenerated struct {
		Streams []struct {
			Index          int    `json:"index"`
			CodecName      string `json:"codec_name,omitempty"`
			CodecLongName  string `json:"codec_long_name,omitempty"`
			Profile        string `json:"profile,omitempty"`
			CodecType      string `json:"codec_type"`
			CodecTagString string `json:"codec_tag_string"`
			CodecTag       string `json:"codec_tag"`
			Width          int    `json:"width,omitempty"`
			Height         int    `json:"height,omitempty"`
		} `json:"streams"`
	}

	type aspectRatio struct {
		Streams []struct {
			Width  int `json:"width"`
			Height int `json:"height"`
		} `json:"streams"`
	}

	ratio := aspectRatio{}
	if err := json.Unmarshal(b.Bytes(), &ratio); err != nil {
		fmt.Println("error:", err)
		return "", err
	}

	return "", nil
}
